#!/bin/bash

JDK_ROOT="/usr/local/jdk"

function select_jdk() {
    if [ ! -d $JDK_ROOT ]; then
        echo "[ERR] Unable find folder $JDK_ROOT." >> /dev/stderr
        exit 1
    fi

    # Check whether each folder under $JDK_ROOT has bin/javac
    i=0
    jdks[0]=""
    for jdk in $(echo $JDK_ROOT/*); do
        if [ ! -d $jdk ]; then
            continue
        fi
        javac_path="${jdk}/bin/javac"
        if [ ! -e $javac_path ]; then
            echo "[WARN] No java found under $jdk" >> /dev/stderr
            continue
        fi
        let i=i+1
        jdks[$i]="${jdk}"
        echo 
        echo ${jdks[*]}
    done

    if [[ ${#jdks[*]} == 1 ]]; then
        echo "[WARN] No JDK found under $JDK_ROOT." >> /dev/stderr
    fi

    echo "Installed JDKs"
    echo "----------------------------------------"
    i=1
    for jdk in ${jdks[*]}; do
        echo "   $i: ${jdk}"
        let i=i+1
    done
    echo "----------------------------------------"
    echo "   q: Quit"
    echo "----------------------------------------"
    let i=i-1

    echo

    while :; do
        read -p "Please select installed JDK [1-$i] or input [q] to quit: " sel
        if [ $sel == "q" ]; then
            exit 0
        fi

        sel=$(($sel + 0))
        if (( $sel >= 1 && $sel <= $i )); then
            echo "JDK under ${jdks[$sel]} was selected."
            export JAVA_HOME=${jdks[$sel]}
            export PATH=$JAVA_HOME/bin:$PATH
            echo "export JAVA_HOME=${jdks[$sel]}" > $HOME/.jdkenv
            echo "export PATH=$JAVA_HOME/bin:\$PATH" >> $HOME/.jdkenv
            echo "JAVA environment settings have been added to \$HOME/.jdkenv."
            return
        fi
    done
}

select_jdk

